services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /usr/bin/supervisord -c /etc/supervisord.conf

  db:
    image: mariadb:12.1.2
    environment:
      MARIADB_DATABASE: leek
      MARIADB_USER: leek
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secretroot
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
