name: Setup CI
description: Sets up the continuous integration environment.

runs:
  using: "composite"
  steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.5"
        tools: composer
        coverage: none
        extensions: pdo, pdo_sqlite, sqlite3

    - name: Install PHP dependencies
      shell: bash
      run: composer install --no-interaction --no-progress --prefer-dist

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      # TODO: uncomment when pnpm action supports caching
      # with:
      # cache: true

    - name: Install Node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build JS/CSS assets
      shell: bash
      run: pnpm build
