name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - name: Build Site
        run: zola build

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan leek.cafe >> ~/.ssh/known_hosts

      - name: Check for Changes
        id: check_rsync
        run: |
          if rsync -avz --delete --dry-run public/ leekcafe@leek.cafe:/var/www/leek.cafe/ | grep -q '^>'; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Deploy with Rsync
        if: env.changes == 'true'
        run: |
          rsync -avz --delete public/ leekcafe@leek.cafe:/var/www/leek.cafe/
