name: Run Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer
          coverage: none
          extensions: pdo, pdo_sqlite, sqlite3

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate --env=testing

      - name: Run tests with Pest
        run: php artisan test
